[Feat]: Update news
delta/dalal-street-server pull request #375
Opened 2022-01-31 15:36 UTC by Hedhav

2022-01-31 16:48 UTC, kelpikz submitted a review, later dismissed
Ur current approach won't work. right now you are
1. deleting the old market event and creating a new one, this will broadcast the edited market event as a new market event
2. you are hard coding 0 for oldStockId in AddMarketEvent action service aka the news will never be edited.

What is actually expected to do. 
1. Add oldNewsId to AddMarketEvent request
2. Create a new function for editing the market event. in that function don't delete the market event, update it.
3. After updating the market event send a relevant message to marketEventStream.

I have basically spilled what you have to do. Do this quickly and send update the pr ASAP

2022-01-31 16:48 UTC, kelpikz commented on models/MarketEvent_test.go
> +	err := AddMarketEvent(3, 0, "Hello", "Hello World", true, "http://www.valuewalk.com/wp-content/uploads/2018/01/bitcoin_1516197589.jpg")
Add tests for updating market events too

2022-01-31 16:48 UTC, kelpikz commented on grpcapi/actionservice/AdminActionService.go
> +	err := models.AddMarketEvent(req.StockId, 0, req.Headline, req.Text, req.IsGlobal, req.ImageUrl)
If u are hard coding 0, the market event will never be updated

2022-02-03 06:12 UTC, siva2204 requested changes

2022-02-03 13:40 UTC, siva2204 approved these changes

2022-02-04 12:13 UTC, siva2204 approved these changes

2022-02-04 12:45 UTC, merged