[Feat]: IPO Feature
delta/dalal-street-server pull request #380
Opened 2022-02-18 19:13 UTC by Hedhav

2022-03-02 07:23 UTC, siva2204 requested changes
todo : integrate with data streams

2022-03-02 07:23 UTC, siva2204 commented on grpcapi/actionservice/OrderActionService.go
> +	IpoBidId, err = models.CreateIpoBid(userId, req.StockId, req.SlotQuantity, req.SlotPrice)
### 
```suggestion

	IpoBidId, err := models.CreateIpoBid(userId, req.StockId, req.SlotQuantity, req.SlotPrice)
```

2022-03-04 11:40 UTC, Hedhav commented on models/Ipo.go
> +	}
but wouldn't these allotment transactions affect the final price of the stock if i save listing price first? the plan was to decide the listing price which will be its value when the market opens after allotment

2022-03-04 11:55 UTC, Hedhav commented on models/Ipo.go
> +			IpoStocksInMarket = uint64(len(openIpoBids))
IpoStocksInMarket = total ipo stocks if oversubscribed, and total stocks bidded for if undersubscribed (rest are deleted)

correction, this line should be:   IpoStocksInMarket = uint64(uint32(len(openIpoBids)) * IpoStock.StocksPerSlot)

2022-03-04 11:58 UTC, Hedhav commented on models/Ipo.go
> +			AllotIpoTransaction := GetTransactionRef(ipoBid.UserId, newStock.Id, IpoAllotmentTransaction, 0, int64(IpoStock.SlotQuantity*IpoStock.StocksPerSlot), 0, -cost, 0)
his reserved cash is being depleted, so isnt it correct? (cost is positive)

2022-03-04 15:22 UTC, siva2204 commented on models/Ipo.go
> +	}
transaction needs stock price, we're doing transaction before calculating the price, which doesnt add up anything to user protfolio

2022-03-19 06:11 UTC, siva2204 approved these changes, later dismissed

2022-03-19 09:55 UTC, satyamurti approved these changes

2022-03-19 09:57 UTC, merged